### ISSUE TITLE
앱 디자인

### ISSUE THREAD

**Issue by Brandnew-one** [Brandnew-one/PerfectDay#4]
* [x] 앱 컬러 설정하기 - 다크모드
* [x] 앱 컬러 설정하기 - 라이트모드
* [x] 앱 아이콘 설정하기
* [ ] 앱 이미지 에셋 설정하기
